### ISSUE TITLE
implementation of scripts as on PatchTST and will it work on kaggle GPU P100 ?

### ISSUE THREAD

**Issue by m6129** [moment-timeseries-foundation-model/moment#1]
Hello, Dear developers

Will dataloader, scripts, etc. be added to this repository as implemented in the PatchTST ?

Do you think your model will work on Kaggle GPU P100 ?

Thanks for your work!

**Comment by KonradSzafer** [comment]
1. We plan to release the research code which includes these in the near future.

**Comment by mononitogoswami** [comment]
Hi Anton,
Thanks for your interest in MOMENT!

We designed this codebase to be extremely lightweight. In the process, we removed a lot of code to handle different datasets, dataloaders, training, and evaluation scripts.

We are working on releasing a bulkier research code, which will include all of that! Until then, I would point you to the early version of our research code on [Anonymous Github](https://anonymous.4open.science/r/BETT-773F/README.md). 

Unfortunately, I haven't worked with Kaggle GPU P100's. MOMENT weights are loaded in bfloat16, which requires NVIDIA Ampere GPUs. More information about the training and experimental infrastructure can be found in our paper!

Please let us know if it doesn't! Again, thanks for your interest in MOMENT!
