### ISSUE TITLE
Performing zero-shot forecasting

### ISSUE THREAD

**Issue by quanpr** [moment-timeseries-foundation-model/moment#17]
Hi, 

Thanks for sharing the good work.

I am using Moment models for zero-shot time series forecasting. The result of forecasting a synthetic sine wave is really bad. I wonder if I've missed anything. Or is Moment intended to work in a fine-tuned manner?

The model I used was:
`model = MOMENTPipeline.from_pretrained(
           'AutonLab/MOMENT-1-large', 
            model_kwargs={
                'task_name': 'forecasting',
                'forecast_horizon': prediction_length,
                'head_dropout': 0.1,
                'weight_decay': 0
            },
)`

The prediction horizon is 64, and the lookback horizon is 512.

![vis-1](https://github.com/moment-timeseries-foundation-model/moment/assets/30205554/bf62cd77-f9ac-419b-bb5b-a8ff292e3e21)

Best,
Pengrui

**Comment by mononitogoswami** [comment]
Hi Pengrui, 
Thanks for you interest in MOMENT!

I see that you are using MOMENT in forecasting mode (`task_name = 'forecasting'`):

```python
model = MOMENTPipeline.from_pretrained( 'AutonLab/MOMENT-1-large',  
model_kwargs={ 'task_name': 'forecasting', 'forecast_horizon': prediction_length, 'head_dropout': 0.1, 'weight_decay': 0 }, )
```

In this mode, a randomly initialized linear layer maps embeddings of historical time series to the forecasting horizon. Hence, the forecasts are essentially random. 

Here's 2 ways to use MOMENT: 
1. (Option) You can initialize MOMENT in reconstruction mode (`task_name = 'reconstruction'`), and use masked reconstruction for forecasting by masking the last 1 or 2 patches, corresponding to a forecasting horizon of $8$ and $16$, respectively. You can use `mask` in the model forward pass, as shown in the [imputation notebook](https://github.com/moment-timeseries-foundation-model/moment/blob/main/tutorials/imputation.ipynb) to reconstruct the patches and forecast future time steps. 
4. (Highly Recommended) You can fine-tune the forecasting head on limited data. 

Let us know if you have any more questions! And thanks again for your interest in MOMENT!

**Comment by quanpr** [comment]
Thanks so much for the detailed illustration!
