### ISSUE TITLE
GPT4TS, TimeNet

### ISSUE THREAD

**Issue by dara1400** [moment-timeseries-foundation-model/moment#19]
Hello
I hope you are doing well.

https://arxiv.org/abs/2402.03885
I wounder can I have to the implementation code of your paper? specially comparison with GPT4TS and TimesNet.

**Comment by mononitogoswami** [comment]
Hi Hamzeh, 
Yes! We have these models implemented! 
We will be releasing MOMENT research code which will include code for baselines, pre-training and much more! Stay tuned for updates, but we expect to release the research code this week 😁!

I'll keep this issue open until we release the research code.

**Comment by dara1400** [comment]
Many Thanks for your reply.
🌺🌺🌺

**Comment by mononitogoswami** [comment]
Hi Hamzeh, 
We just released the MOMENT research code (https://github.com/moment-timeseries-foundation-model/moment-research), which have TimesNet and GPT4TS implemented!

Cheers,
Mononito

**Comment by dara1400** [comment]
Hello
Very nice
Thanks
🌷🌷🌷
