### ISSUE TITLE
Issues with README Links and Tutorial File Paths

### ISSUE THREAD

**Issue by Isaka-code** [moment-timeseries-foundation-model/moment#2]
Hello,

I've noticed a couple of issues in the repository that need addressing:

1. **Incorrect Links in README:**
   - The links for "Anomaly Detection" and "Embedding" in the README are incorrect. Other links such as "Forecasting", "Classification", and "Imputation" are correctly set.

2. **Missing Tutorial Notebooks:**
   - The link for the embedding notebook is broken. It appears that the intended file `embedding.ipynb` is missing under `moment/tutorials/`. However, the file `representation_learning.ipynb` is present.
   - Similarly, the path for the anomaly detection notebook is incorrect. The current path is listed as `moment/.tutorials/anomaly_detection.ipynb`, but the correct path should be `moment/tutorials/anomaly_detection.ipynb`.

Would it be possible to update the README links and ensure the correct tutorial notebooks are available at the specified paths?

Thank you for addressing these issues.

**Comment by KonradSzafer** [comment]
Hi @Isaka-code, thanks for the suggestions! Fixed!

**Comment by Isaka-code** [comment]
Hi @KonradSzafer , thank you for your assistance! I will go ahead and close this issue now.
