### ISSUE TITLE
GPU, single-node multi-GPU, multi-node multi-GPU support for forecast generation

### ISSUE THREAD

**Issue by ryuta-yoshimatsu** [moment-timeseries-foundation-model/moment#24]
It is not clear from the documentation and the sample code, if the forecast generation can be performed on a GPU, multiple GPUs, or multiple GPUs in multiple nodes. If this is the case, please add some descriptions on how to achieve this.

**Comment by mononitogoswami** [comment]
Hi Ryuta, 
Thanks for your interest in MOMENT!
Depending on the batch size, which is typically in the range of 16--64 during fine-tuning, MOMENT can be fine-tuned on a single GPU. For reference, all the tutorials were run on a single NVIDIA A6000 GPU with 48 GB RAM. 
With that said, we are about to release a tutorial to fine-tune MOMENT using parameter efficient fine-tuning to reduce GPU memory usage, and also enabling multi-GPU training. Stay tuned! 

I'll keep this issue open until we release the tutorial!

**Comment by ryuta-yoshimatsu** [comment]
Hi! Thanks for the prompt reply and I'm looking forward to the tutorial for fine-tuning.

My question was more on the inference side rather than the training. Is there a way to assign a GPU to make an inference (i.e. `model(context, input_mask=input_mask)`) or even distribute an inference across multiple GPUs?

I highly respect the work you are doing!

**Comment by mononitogoswami** [comment]
Hi Ryuta,
We added tutorials recently which would enable you to use multiple GPUs. 

I am closing this issue at this point.

Thanks for your interest in MOMENT, and let us know if you have any questions!

Best,
Mononito

**Comment by ooooooover** [comment]
Hi Mononito，
Can you tell me where the code is for how to call multiple gpu's, I don't see a corresponding tutorial for it.

**Comment by mononitogoswami** [comment]
Hi @ooooooover, You can follow this notebook: https://github.com/moment-timeseries-foundation-model/moment/blob/main/tutorials/ptbxl_classification.ipynb for multi-GPU training and PEFT fine-tuning.

Best,
Mononito

**Comment by ooooooover** [comment]
Thank you for your reply.
