### ISSUE TITLE
load data from CSV zero-shot forecasting

### ISSUE THREAD

**Issue by mohamedyasser** [moment-timeseries-foundation-model/moment#25]
Hi,

Thanks for sharing the good work.

can any one share an example of loading data from csv file with two culomn time => for timestab and value => for target value

**Comment by mononitogoswami** [comment]
Hi Mohamed, 
Thanks for your interest in MOMENT! Unfortunately, MOMENT does not do zero-shot forecasting. I would recommend loading data with our dataloader which accepted CSVs (or check out our general dataloaders in the MOMENT Research code, https://github.com/moment-timeseries-foundation-model/moment-research), and fine-tuning a forecasting head.

With that said, there's a lot of recent exciting research on models which are tailored for zero-shot time series forecasting, Chronos (https://github.com/amazon-science/chronos-forecasting), TimesFM (https://github.com/google-research/timesfm), Uni2TS (https://blog.salesforceairesearch.com/moirai/), Timer (https://github.com/thuml/Large-Time-Series-Model). I would also recommend taking a look at them.

Best, 
Mononito
