### ISSUE TITLE
data location hardwired

### ISSUE THREAD

**Issue by microprediction** [moment-timeseries-foundation-model/moment#27]
Just a comment that the location of example data is hardwired and assumes we are running from, say a pip install -e setup, not as a separate package. 

          self.full_file_path_and_name = "../data/ETTh1.csv"

Solution would be to include this optional in __init__

**Comment by mononitogoswami** [comment]
Hi Peter, 
Different datasets had to be handed differently, so to minimize and simplify code in this repository we hard coded a few things. With that said, now we have made MOMENT research code public (https://github.com/moment-timeseries-foundation-model/moment-research), which would be able to handle all datasets that we have used in the paper, and more!

Best,
Mononito
