### ISSUE TITLE
Scale data before fine-tuning

### ISSUE THREAD

**Issue by rt-adesai** [moment-timeseries-foundation-model/moment#29]
When fine-tuning for a forecasting task, is the dataset supposed to be scaled? The Informer dataset example shows standard scaling but not sure if that's the recommended preprocessing step.

**Comment by mononitogoswami** [comment]
Hi, 
Thanks for your interest in MOMENT, and I apologize for the delay in responding!

We standard scaled all forecasting datasets during benchmarking, and would recommend doing the same before fine-tuning on your dataset too! 

Let us know if you have any more questions on pre-processing. I'll close this issue, but feel free to open it with more questions!

Best,
Mononito
