### ISSUE TITLE
The early release of research code on Anonymous Github is expired

### ISSUE THREAD

**Issue by windsoryin** [moment-timeseries-foundation-model/moment#31]
The early release of research code on Anonymous Github is expired. About a week ago, it was still available. Could you release the new link to  the research code? Thanks~

**Comment by mononitogoswami** [comment]
Hi Wenjie, 
We are about to release the research code of MOMENT on Github shortly, which would succeed the Anonymous Github code. However, for your convenience we have reactivated access to the Anonymous Github! 

Thanks for your interest in MOMENT!

Best, 
Mononito

**Comment by windsoryin** [comment]
Hi Mononito,
Thanks for your generous sharing of the MOMENT early release code.  Your great works have inspired me a lot.
Wish you have a nice day!

Cheers,
Windsor
