### ISSUE TITLE
how can run this model in offline mode?

### ISSUE THREAD

**Issue by beileiyuyue** [moment-timeseries-foundation-model/moment#32]
when I run this model,I got this:
OSError: We could not connect to ' https://huggingface.co/ To load this file, could not find it in the cached files and it looks like Google/plan t5 large is not the path to a directory containing a file named config.json
Checkout your internet connection or see how to run the library in offline mode at ' https://huggingface.co/docs/transformers/installation#offline -Mode

What other files do I need to download before using this model?

**Comment by lavender-ER** [comment]
bro,did you solve it?

**Comment by mononitogoswami** [comment]
Hello, 
Thanks for your interest in MOMENT! We possibly fixed this issue with the latest pull request. 
I am closing this issue, but please don't hesitate to open another one if you face more problems!

Best, 
Mononito
