### ISSUE TITLE
How to get embeddings for time series longer than 512 timesteps 

### ISSUE THREAD

**Issue by Aya-2001** [moment-timeseries-foundation-model/moment#35]
I need to get embeddings for time series that are way longer than 512 timestamps.
Is it possible to do that with MOMENT ?

**Comment by mononitogoswami** [comment]
Hi, Thanks for your interest in MOMENT!

Depending on the length of the time series, here are some suggestions: 

1. **Down sampling longer time series** -- The MOMENT research repository (https://github.com/moment-timeseries-foundation-model/moment-research) has some way to down sample time series such as sampling the rightmost, left most or a random subset of 512 time steps, cubic spline interpolation, and uniform down sampling. 
2. **Modeling using recurrence**: MOMENT may be used in a sliding window fashion for long time series. A long time series can be split into disjoint chunks of 512 time steps, and embeddings from each chunk can be concatenated (or averaged) for predictions.


A combination of these tricks may work better for your use case.

This is a hard problem in general, and our team is doing research to extend the context length of MOMENT. Stay tuned for updates, and thank you so much for your interest!

Best, 
Mononito

**Comment by mononitogoswami** [comment]
I will close this issue for now, but please don't hesitate to re-open the issue or Open another one should you have a question!
