### ISSUE TITLE
Is it normal to have embeddings longer than the original time series ?

### ISSUE THREAD

**Issue by Aya-2001** [moment-timeseries-foundation-model/moment#36]
We get embeddings of 1024 timestamps for time series of length 512 using MOMENT.
Aren't embeddings supposed to be shorter than original timeseries as we want to reduce dimension ?

**Comment by mononitogoswami** [comment]
Hi, 
This is a great question! Embeddings are generally used to learn useful information from raw data. However, embeddings are an automatic featurization of raw time series, and do not necessarily have to be smaller than the raw time series. Imagine manual feature engineering -- you may want to include raw time series feature, frequency-domain features, as well as other distributional features, which together can be more than just raw time domain features alone. 

Best,
Mononito
