### ISSUE TITLE
We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like google/flan-t5-large is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

### ISSUE THREAD

**Issue by lavender-ER** [moment-timeseries-foundation-model/moment#39]
I download this model from huggingface,and put them into /home/ahu123/.cache/huggingface/hub/models--AutonLab--MOMENT-1-large/. 
from momentfm import MOMENTPipeline

model = MOMENTPipeline.from_pretrained(
    "/home/ahu123/.cache/huggingface/hub/models--AutonLab--MOMENT-1-large/", local_files_only=True,
    model_kwargs={
        'task_name': 'forecasting',
        'forecast_horizon': 192,
        'head_dropout': 0.1,
        'weight_decay': 0,
        'freeze_encoder': True, # Freeze the patch embedding layer
        'freeze_embedder': True, # Freeze the transformer encoder
        'freeze_head': False, # The linear forecasting head must be trained
    },
)

but get 

We couldn't connect to 'https://huggingface.co/' to load this file, couldn't find it in the cached files and it looks like google/flan-t5-large is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by mononitogoswami** [comment]
Hello, 
Thanks for your interest in MOMENT! We have fixed this issue in the latest pull request. Let us know if the issue has resolved for you. I am closing the issue for now, but please don't hesitate to (re-)open an issue if you face any more problems!

Best, 
Mononito
