### ISSUE TITLE
TypeError: MOMENTPipeline.__init__() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by XinyuanLiao** [moment-timeseries-foundation-model/moment#40]
Hi,

When I try to run the blow code on my mac, I meet the above error. But it's ok when I run it on colab.

```
from momentfm import MOMENTPipeline

model = MOMENTPipeline.from_pretrained(
    "AutonLab/MOMENT-1-large",
    model_kwargs={
        'task_name': 'classification',
        'n_channels': 1,
        'num_class': 5
    }, # We are loading the model in `classification` mode
)
model.init()
print(model)
```

**Comment by audreyeternal** [comment]
same problem.

**Comment by audreyeternal** [comment]
@XinyuanLiao, I think the most possible reason would be the internet issue. [here](https://github.com/huggingface/huggingface_hub/blob/9a9b8c137dbe27e553f85e737a14289479a86641/src/huggingface_hub/hub_mixin.py#L514) the model will try to download the config file from the hub and [here](https://github.com/huggingface/huggingface_hub/blob/9a9b8c137dbe27e553f85e737a14289479a86641/src/huggingface_hub/hub_mixin.py#L553) the `config` will be merged into `model_kwargs`. So if it fails to retrieve the config file, the above mentioned error will show up.

**Comment by mononitogoswami** [comment]
Hi Xinyuan, 
The latest version of the model should not have this issue. 

Let us know if you have any questions!

Best,
Mononito
