### ISSUE TITLE
Import error with `'split_torch_state_dict_into_shards' from 'huggingface_hub'`

### ISSUE THREAD

**Issue by julian-fong** [moment-timeseries-foundation-model/moment#41]
With huggingface-hub version 0.19.4, some failures are occuring due to a failed import in the library. Would it be possible to relax the boundaries of this package to fix the import? Related issue https://github.com/run-llama/llama_index/discussions/14605

**Comment by mononitogoswami** [comment]
Hi Julian, 
Thanks for your interest in MOMENT. I updated huggingface hub, and released a new version. Let me know if it works for you! I'll close this issue, but please don't hesitate to open it if you face more problems.

Best,
Mononito
