### ISSUE TITLE
time series longer than 512 timesteps

### ISSUE THREAD

**Issue by audreyeternal** [moment-timeseries-foundation-model/moment#45]
Hi, I want to process a time series with around 1000 time steps. But based on the tutorial, seems like it can only handle the input with 512 data points. So I am wondering how to deal with this scenario? Thank you!

**Comment by audreyeternal** [comment]
Found a related issue here: #22. But I am not sure if using downsampling in this case will lose some high frequency information?

**Comment by audreyeternal** [comment]
Found another related issue: #35. Current workaround: 1. down sampling; 2. sliding window.

**Comment by mononitogoswami** [comment]
Hi Yu, 
Thanks for your interest in MOMENT!

We are currently working on MOMENT with extended context length. 

Currently, the work around you suggested are exactly the ones we use in practice. 

Let us know if you have any more questions, and feel free to re-open this discussion should you learn of a better way to model longer time series. 

Best,
Mononito
