### ISSUE TITLE
Long-term-forecasting results in ETTm1\weather\electic dataset is not as good as report

### ISSUE THREAD

**Issue by shaozheliu** [moment-timeseries-foundation-model/moment#47]
Thank you for the author's contribution. I have reproduced the results on the ETTh1 dataset. However, the performance on the ETTm1/weather/electric dataset is not as good as reported. Could this be due to issues with my dataset reading, or was there any special processing in your experiments? Thank you for your response.

![image](https://github.com/user-attachments/assets/650a438a-a8e1-4f94-bcd3-dcf28da46bf6)

could you provide the hyperparameters setting list when training LP in these datasets?

**Comment by mononitogoswami** [comment]
Hi Shaozhe, 
Thanks for your interest in MOMENT. I would recommend checking out our MOMENT-Research code where you will find all the code necessary to reproduce the forecasting results, including dataset pre-processing, fine-tuning code and hyper-parameters: https://github.com/moment-timeseries-foundation-model/moment-research

Let us know if you have any more questions!

Best,
Mononito
