### ISSUE TITLE
Library name conflicts

### ISSUE THREAD

**Issue by dafmdev** [moment-timeseries-foundation-model/moment#5]
The library is called "moment" but there is already a [library with this name](https://pypi.org/project/moment/) and when I try to import its library, the other one that I already had installed is imported.

**Comment by KonradSzafer** [comment]
Hi @dafmdev, thanks for pointing this out, we were not aware of this package and will change the name in the coming days.

**Comment by josuablejeru** [comment]
@dafmdev Depending on your package manager you can install the package using the GitHub URL.

**Comment by KonradSzafer** [comment]
Hi @dafmdev! We renamed the package to `momentfm`, shouldn't cause conflicts anymore!
