### ISSUE TITLE
Unable to find the tiltAPB2 dataset in the anomaly_detection tutorials

### ISSUE THREAD

**Issue by zuijiayule** [moment-timeseries-foundation-model/moment#53]
According to the tutorial, the original data is the tiltAPB2 dataset from the [UCR Anomaly Archive](https://www.cs.ucr.edu/%7Eeamonn/time_series_data_2018/), but I don't see any data with the word "tiltAPB2" in the entire archive at the source address. 
In this tutorial, the original data in "198_UCR_Anomaly_tiltAPB2_50000_124159_124985.out" has only two columns. Because label is not involved in the import of the model and is only used for evaluation (through adjbestf1), preds is reconstructed according through the model. So what does the original data represent?

**Comment by mononitogoswami** [comment]
Hi, 
All our datasets are taken from [TSB-UAD](https://github.com/TheDatumOrg/TSB-UAD) which pre-processes multiple time series anomaly detection datasets in a unified format, including the UCR Anomaly Archive. 

In this case the original data is a time series along with anomaly labels. It is taken from the UCR Anomaly Archive as you mentioned.

The goal is to identify anomalous time steps given input time series. The training part of the time series is anomaly free. 

Does that answer your question? 

Best,
Mononito

**Comment by zuijiayule** [comment]
Hi I had to reopen the issue in order to point out some of your linking errors.

In your anomaly detection tutorial you use this address [UCR Anomaly Archive](https://www.cs.ucr.edu/%7Eeamonn/time_series_data_2018/) as the source of the dataset but the page is UCR Time Series Classification Archive.
The correct dataset source should be: https://www.cs.ucr.edu/~eamonn/time_series_data_2018/UCR_TimeSeriesAnomalyDatasets2021.zip

For [TSB-UAD](https://github.com/TheDatumOrg/TSB-UAD),  they still use the same data structure as you, i.e. value + label (0 or 1). 
My question is, how do you guys convert the raw data into e.g. . /data in an xx.out file. Or did you just simply use the UCR Anomaly Archive and the labels already defined in the different data sources in it.

Looking forward to your reply, thanks a lot!
