### ISSUE TITLE
moment vs moment-research

### ISSUE THREAD

**Issue by jaztsong** [moment-timeseries-foundation-model/moment#54]
Hello,

Apologies for using this resource for a consultation.

I plan to adapt `moment` for a timestep annotation task, where I need to assign a label to each time point rather than to the entire sequence. I’m currently reviewing the `moment-research` code to find ways to integrate my application and dataset. The code is quite professional and employs advanced techniques, but it is a bit overwhelming.

Could you advise on which codebase would be more suitable for this purpose—`moment` or `moment-research`?

Thank you for your help.

**Comment by mononitogoswami** [comment]
Hi Jaztsong, 
Thanks for your interest in MOMENT. I would recommend going with the `moment` repository-- it contains the minimum code necessary to run MOMENT. `moment-research` is to pre-train foundation models and reproduce our experiments. 

Best,
Mononito
