### ISSUE TITLE
How to pretrain with the time series data shorter than 512?

### ISSUE THREAD

**Issue by Wangzj000** [moment-timeseries-foundation-model/moment#65]
Hello! Your work is really impressive and I am reading your paper.
However, I am confused when noting that some data of Monsah datasets and UCR datasets is shorter than 512.
Could you explain how to deal with the data in detail. It will really help me to understand the Moment model.

**Comment by mononitogoswami** [comment]
Hi, 
Thanks for your interest in MOMENT!

We handle short time series in one of two ways: we upsamples time series where the shape matters, e.g. classification time series in UCR, and pad time series where frequency is important, e.g. time series for forecasting. 

I would recommend looking at the classification and forecasting dataset classes [here](https://github.com/moment-timeseries-foundation-model/moment-research/tree/main/moment/data) for more information.

Best,
Mononito
