### ISSUE TITLE
Reproduce zero-shot anomaly detection

### ISSUE THREAD

**Issue by xihuachen9804** [moment-timeseries-foundation-model/moment#66]
Hi, thanks for your good work.
I have some problems in reproducing your zero-shot anomaly detection work.

I downloaded your code and paper, followed [tutorials/anomaly_detection.ipynb](https://github.com/moment-timeseries-foundation-model/moment/blob/main/tutorials/anomaly_detection.ipynb) to reproduce the zero-shot anomaly detection results.
Since the calculation code for VUS-ROC is not provided in [moment](https://github.com/moment-timeseries-foundation-model/moment), I copied the complete metrics calculation code from [moment-reseach](https://github.com/moment-timeseries-foundation-model/moment-research/blob/main/moment/utils/anomaly_detection_metrics.py).
In the final result,  adj.f1 results can be reproduced, but the VUS- ROC results are much different from the paper. 
I only get 0.61984 on VUS- ROC，while in the paper it is 0.750.

**Comment by mononitogoswami** [comment]
Hi Xi, 
I used this  [bash script](https://github.com/moment-timeseries-foundation-model/moment-research/blob/main/reproduce/zero_shot/anomaly_detection.sh) which uses this [script](https://github.com/moment-timeseries-foundation-model/moment-research/blob/main/scripts/zero_shot/anomaly_detection.py) and this [config file](https://github.com/moment-timeseries-foundation-model/moment-research/blob/main/configs/anomaly_detection/zero_shot.yaml) to get zero-shot anomaly detection results using MOMENT-Large. 

I hope this helps you reproduce the results!

**Comment by Rango-Zhang-Hang** [comment]
> MOMENT-Large.

Hi there. Thank you for sharing this excellent work! Yet I also notice this bug. The MOMENT-large weight and model could not reproduce the zero-shot results in the original paper. 

You suggest using the moment-research repo, is there any difference with moment?
