### ISSUE TITLE
Time Series PILE for 2 epochs Pretrain: channels alignments?

### ISSUE THREAD

**Issue by Rango-Zhang-Hang** [moment-timeseries-foundation-model/moment#68]
Hi,
Thank you for sharing such great work in Time Series.

I am interested in your public time series data collection as the Time Series Pile. Yet I encountered a technical issue: they hold different channels. Especially for long-horizon forecasting tasks, as you already mentioned in Appendix E, channels vary from 7 to 862.

So, how do you manage to re-organize these data in the pertaining stage?

Thanks.

PS: Your paper provides thorough details and I truly appreciate that.

**Comment by mononitogoswami** [comment]
Hi Rangbo, 
Thanks for your interest in MOMENT!

During pre-training, we ensure that the dataloaders only provide univariate time series. The dataloaders used to train and evaluate MOMENT can be found [here](https://github.com/moment-timeseries-foundation-model/moment-research/tree/main/moment/data).

In summary, for forecasting datasets we only consider the target time series (not the covariates during pre-training), and for classification datasets we reshape the different covariates along the batch dimensions $(N, C, T) \rightarrow (N*C, 1, T)$, where $N$ is the number of time series in a dataset, $C$ is the number of channels and $T$ is the length of each time series. Anomaly detection datasets from TSB-UAD are univariate. 

Note that this is only _one way_ to go about doing this!

Best,
Mononito

**Comment by Rango-Zhang-Hang** [comment]
Hi Mononito,

Thank you for your patient reply! It helps a lot.

Good luck with your future work!

Best, 
Rango
