### ISSUE TITLE
Return None result on forecasting filed

### ISSUE THREAD

**Issue by snakei14702** [moment-timeseries-foundation-model/moment#7]
Dear Team,

Thank you for this wonderful model release. I encountered a few issues at the beginning of the tutorials.

When I ran the code for the forecasting tutorial, the model returned None in the forecasting field but produced a result in the reconstruction field. Therefore, I am unable to proceed with the rest of the tutorials.

<img width="405" alt="result" src="https://github.com/moment-timeseries-foundation-model/moment/assets/21195500/c6ceb5d3-5a41-4d4a-b4b5-fa5ff0908cf8">

a similar result in the tutorial on classification:
<img width="415" alt="result 2" src="https://github.com/moment-timeseries-foundation-model/moment/assets/21195500/e6908159-0052-4a89-8f94-e625d3b29ae4">

thank for you again!

**Comment by mononitogoswami** [comment]
Hi @snakei14702, Thanks for your interest in MOMENT! Can you try restarting and re-running your notebooks? We have tested the notebooks, and this behavior is not expected.

**Comment by snakei14702** [comment]
Sorry for taking up your time, but I reloaded the model today and surprisingly, it can be used normally again… I should delete this post, I apologize once again!

**Comment by snakei14702** [comment]
Sorry for taking up your time, but I reloaded the model today and surprisingly, it can be used normally again… I should delete this post, I apologize once again!

**Comment by mononitogoswami** [comment]
No worries, glad it worked!

**Comment by Rango-Zhang-Hang** [comment]
> Sorry for taking up your time, but I reloaded the model today and surprisingly, it can be used normally again… I should delete this post, I apologize once again!

Would you mind sharing how you made it? I still suffer from this None result.
