### ISSUE TITLE
Python version 

### ISSUE THREAD

**Issue by RubenPhy** [moment-timeseries-foundation-model/moment#9]
Hi!

I think it could be useful to know the python version required, because for me, it only works with python 3.10. 
With python 3.12 there is a problems with the module distutils, which it is required to implement your model, but it is not in python 3.12, and with python 3.11, your pytorch version (2.0.1) is not compatible, I think. 

Thanks again!

**Comment by KonradSzafer** [comment]
Hi @RubenPhy, thanks for raising this! Your insights are great, we will update the readme and try to make it work with other Python versions.

**Comment by mononitogoswami** [comment]
Hi @RubenPhy, 
Thanks for your interest in MOMENT!
The model should work for Python 3.11 (now added as an image shield badge), and PyTorch 2.0.1! Let us know if this doesn't work for you! I am marking this issue as resolved for now.
